*** empty log message ***

diff --git a/smx/configure b/smx/configure
--- a/smx/configure
+++ b/smx/configure
@@ -1037,6 +1037,8 @@ Optional Packages:
   --with-apxs[=FILE]      Build shared Apache module.  FILE is the
                           optional pathname to the Apache apxs tool;
                           defaults to "apxs".
+  --with-apr[=FILE]     Used to determine which version of Apache we
+                          are build for.
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -5064,7 +5066,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5067 "configure"' > conftest.$ac_ext
+  echo '#line 5069 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5593,7 +5595,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5596: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5598: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6777,7 +6779,7 @@ linux-gnu*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*)
-    echo '#line 6780 "configure"' > conftest.$ac_ext
+    echo '#line 6782 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7449,7 +7451,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7452 "configure"
+#line 7454 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7547,7 +7549,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7550 "configure"
+#line 7552 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11851,7 +11853,83 @@ echo "${ECHO_T}\"$APXS Version 2.X\"" >&6
 fi;
 
 
-CPPFLAGS="$CPPFLAGS -I $APXS_INCLUDE"
+  echo "$as_me:$LINENO: checking for apr" >&5
+echo $ECHO_N "checking for apr... $ECHO_C" >&6
+
+# Check whether --with-apr or --without-apr was given.
+if test "${with_apr+set}" = set; then
+  withval="$with_apr"
+
+      if test "$APACHE2" = "yes";
+      then
+        if test "$withval" = "yes";
+        then
+          for i in /usr/sbin /usr/local/apache/bin /usr/local/apache2/bin \
+            /usr/local/apache/sbin /usr/local/apache2/sbin /usr/bin ; do
+            if test -f "$i/apr-config"; then
+              APR="$i/apr-config"
+            fi
+          done
+          if test "$APR" = ""; then
+            { { echo "$as_me:$LINENO: error: \"could not find apr-config\"" >&5
+echo "$as_me: error: \"could not find apr-config\"" >&2;}
+   { (exit 1); exit 1; }; }
+          else
+            echo "$as_me:$LINENO: result: \"$APR\"" >&5
+echo "${ECHO_T}\"$APR\"" >&6
+          fi
+        else
+          APR="$withval"
+          APR_VERSION="`$APR -V | grep 1.3`"
+          if test -n "$APR_VERSION"; then
+            echo "$as_me:$LINENO: result: \"$APR Version $APR_VERSION\"" >&5
+echo "${ECHO_T}\"$APR Version $APR_VERSION\"" >&6
+          else
+            echo "$as_me:$LINENO: result: \"$APR Version 2.X\"" >&5
+echo "${ECHO_T}\"$APR Version 2.X\"" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define APACHE2 1
+_ACEOF
+
+          fi
+        fi
+        APR_INCLUDE="-I`$APR --includedir`"
+        APR_LIBS="`$APR --libs`"
+      else
+        { { echo "$as_me:$LINENO: error: \"no need for apr-config\"" >&5
+echo "$as_me: error: \"no need for apr-config\"" >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+
+else
+
+      if test "$APACHE2" = "yes";
+      then
+        for i in /usr/bin /usr/local/apache/bin /usr/local/apache2/bin ; do
+          if test -f "$i/apr-config"; then
+            APR="$i/apr-config"
+          fi
+        done
+        if test "$APR" = ""; then
+          { { echo "$as_me:$LINENO: error: \"could not find apr-config\"" >&5
+echo "$as_me: error: \"could not find apr-config\"" >&2;}
+   { (exit 1); exit 1; }; }
+        else
+          echo "$as_me:$LINENO: result: \"$APR\"" >&5
+echo "${ECHO_T}\"$APR\"" >&6
+        fi
+        APR_INCLUDE="-I`$APR --includedir`"
+        APR_LIBS="`$APR --libs`"
+      else
+        echo "$as_me:$LINENO: result: \"no need for apr-config\"" >&5
+echo "${ECHO_T}\"no need for apr-config\"" >&6
+      fi
+
+fi;
+
+
+CPPFLAGS="$CPPFLAGS -I $APXS_INCLUDE -I $APR_INCLUDE"
 
 # Checks for header files.
 
