modified to work on debian

diff --git a/smx/configure b/smx/configure
--- a/smx/configure
+++ b/smx/configure
@@ -23381,7 +23381,12 @@ if test "${with_apxs+set}" = set; then
   withval="$with_apxs"
 
     if test "$withval" = "yes"; then
-      for i in /usr/local/apache/bin /usr/local/apache2/bin /usr/sbin ; do
+      for i in /usr/local/apache/bin /usr/local/apache2/bin /usr/sbin /usr/bin ; do
+        if test -f "$i/apxs2"; then
+          APXS="$i/apxs2"
+        fi
+      done
+      for i in /usr/local/apache/bin /usr/local/apache2/bin /usr/sbin /usr/bin ; do
         if test -f "$i/apxs"; then
           APXS="$i/apxs"
         fi
@@ -23400,16 +23405,17 @@ echo "$as_me: error: \"could not find apxs\"" >&2;}
       fi
     fi
 
+    HTTPD_EXE="`$APXS -q TARGET`"
     HTTPD_DIR="`$APXS -q SBINDIR`"
-    HTTPD="$HTTPD_DIR/httpd"
+    HTTPD="$HTTPD_DIR/$HTTPD_EXE"
     APXS_CC="`$APXS -q CC`"
     APXS_INCLUDE="`$APXS -q INCLUDEDIR`"
     APXS_CONFDIR="`$APXS -q SYSCONFDIR`"
     APACHE_LIBEXECDIR="`$APXS -q libexecdir`"
 
     if test "$HTTPD" = ""; then
-      { { echo "$as_me:$LINENO: error: \"could not find httpd from apxs\"" >&5
-echo "$as_me: error: \"could not find httpd from apxs\"" >&2;}
+      { { echo "$as_me:$LINENO: error: \"could not find $HTTPD_EXE (httpd) from apxs\"" >&5
+echo "$as_me: error: \"could not find $HTTPD_EXE (httpd) from apxs\"" >&2;}
    { (exit 1); exit 1; }; }
     else
       HTTPD_VERSION="`$HTTPD -V | grep 1.3`"
@@ -23431,26 +23437,33 @@ echo "${ECHO_T}\"$APXS Version 2.X\"" >&6
 else
 
       for i in /usr/local/apache/bin /usr/local/apache2/bin /usr/sbin ; do
+        if test -f "$i/apxs2"; then
+          APXS="$i/apxs2"
+        fi
+      done
+      for i in /usr/local/apache/bin /usr/local/apache2/bin /usr/sbin ; do
         if test -f "$i/apxs"; then
           APXS="$i/apxs"
         fi
       done
+      if test "$APXS" = ""; then
       if test "$APXS" = ""; then
         { { echo "$as_me:$LINENO: error: \"could not find apxs\"" >&5
 echo "$as_me: error: \"could not find apxs\"" >&2;}
    { (exit 1); exit 1; }; }
       fi
 
+      HTTPD_EXE="`$APXS -q TARGET`"
       HTTPD_DIR="`$APXS -q SBINDIR`"
-      HTTPD="$HTTPD_DIR/httpd"
+      HTTPD="$HTTPD_DIR/$HTTPD_EXE"
       APXS_CC="`$APXS -q CC`"
       APXS_INCLUDE="`$APXS -q INCLUDEDIR`"
       APXS_CONFDIR="`$APXS -q SYSCONFDIR`"
       APACHE_LIBEXECDIR="`$APXS -q libexecdir`"
 
       if test "$HTTPD" = ""; then
-        { { echo "$as_me:$LINENO: error: \"could not find httpd from apxs\"" >&5
-echo "$as_me: error: \"could not find httpd from apxs\"" >&2;}
+        { { echo "$as_me:$LINENO: error: \"could not find $HTTPD_EXE (httpd) from apxs\"" >&5
+echo "$as_me: error: \"could not find $HTTPD_EXE (httpd) from apxs\"" >&2;}
    { (exit 1); exit 1; }; }
       else
         HTTPD_VERSION="`$HTTPD -V | grep 1.3`"
